packages/comet/src/components/index.ts
packages/comet/src/components/prose/index.ts
packages/comet/src/components/prose/prose.stories.tsx
packages/comet/src/components/prose/prose.test.tsx
packages/comet/src/components/prose/prose.tsx

This is a simple component called Prose that returns a select tag with the usa-prose class. It has a default story that's viewable in Storybook.
https://metrostarsystems.atlassian.net/browse/WAR-51
Using this component to wrap text will apply the basic styling that USWDS has set up for prose.
We ran simple tests to make sure the component renders with its props correctly. We also ran the app to make sure the storybook pages display correctly in Firefox.

War-51: New Prose component

---

.github/workflows/publish-package.yaml
package.json

Updates to automate publishing to NPM upon publishing a new release.
- Added publish package github action
- Added scripts to package.json for publishing
N/A
Establish a consistent, scalable approach to publishing npm packages
Scripts ran locally
N/A

WAR-26: Add automated NPM publish

---

packages/comet-data-viz/src/components/bar-graph/bar-graph.stories.tsx
packages/comet-uswds/src/components/table/table.tsx

Fix downstream accessibility issue.
- Updated table component to only enable sorting if sortable and not already sorted.
- Unrelated Lint fix
N/A
- Accessibility/functionality fix
- Verified locally
N/A

CSG-770: Fix Comet USWDS Table Accessibility issue

---

packages/comet-uswds/src/components/table/table.stories.tsx
packages/comet-uswds/src/components/table/table.test.tsx
packages/comet-uswds/src/components/table/table.tsx

Fixes and updates noticed during use of component.
- Fixed issue causing sorting to not work on tables due to the table.off function removing sorting after render
- Added borderless and striped configurations to table
N/A
- Resolve issues
- Add functionality
- Verified locally in Storybook, Starter App, and multiple other Starter App based apps
N/A

CSG-952: USWDS Table Updates and Fixes

---

package-lock.json
packages/comet-uswds/package.json

Update to next minor release.
- Removed deprecated Dropdown component
- Update to latest USWDS version (3.6.0)
N/A
N/A
N/A
N/A

Release: 1.4.0

---

package-lock.json
packages/comet-extras/package.json
packages/comet-extras/src/components/data-table/data-table.stories.tsx
packages/comet-extras/src/components/data-table/data-table.style.css
packages/comet-extras/src/components/data-table/data-table.test.tsx
packages/comet-extras/src/components/data-table/data-table.tsx
packages/comet-extras/src/components/data-table/index.ts
packages/comet-extras/src/components/index.ts

Add a more flexible and functional react data table to Comet
- Added [TanStack Table](https://tanstack.com/table/v8) package to project
- Added custom component based on TanStack table to Comet Extras, providing flexible data rendering, sorting, and paging
- Added Stories for new Data Table to Extras section
- Added Unit tests for coverage
N/A
- To provide a more customized data table for use in projects
- Unit Testing
- Verified no accessibility issues

CSG-818: Add Advanced Datatable Component to Comet Extras

---

packages/comet-uswds/src/components/accordion/accordion.stories.tsx
packages/comet-uswds/src/components/accordion/accordion.test.tsx
packages/comet-uswds/src/components/accordion/accordion.tsx
packages/comet-uswds/src/components/accordion/index.ts
packages/comet-uswds/src/components/breadcrumb/breadcrumb.stories.tsx
packages/comet-uswds/src/components/breadcrumb/breadcrumb.test.tsx
packages/comet-uswds/src/components/breadcrumb/breadcrumb.tsx
packages/comet-uswds/src/components/breadcrumb/index.ts
packages/comet-uswds/src/components/combo-box/combo-box.stories.tsx
packages/comet-uswds/src/components/combo-box/combo-box.test.tsx
packages/comet-uswds/src/components/combo-box/combo-box.tsx
packages/comet-uswds/src/components/combo-box/index.ts
packages/comet-uswds/src/components/error-messages/error-messages.stories.tsx
packages/comet-uswds/src/components/error-messages/error-messages.test.tsx
packages/comet-uswds/src/components/error-messages/error-messages.tsx
packages/comet-uswds/src/components/error-messages/index.ts
packages/comet-uswds/src/components/index.ts
packages/comet-uswds/src/components/process-list/index.ts
packages/comet-uswds/src/components/process-list/process-list.stories.tsx
packages/comet-uswds/src/components/process-list/process-list.test.tsx
packages/comet-uswds/src/components/process-list/process-list.tsx
packages/comet-uswds/src/components/select/index.ts
packages/comet-uswds/src/components/select/select.stories.tsx
packages/comet-uswds/src/components/select/select.test.tsx
packages/comet-uswds/src/components/select/select.tsx
packages/comet-uswds/src/components/side-navigation/index.ts
packages/comet-uswds/src/components/side-navigation/side-navigation.stories.tsx
packages/comet-uswds/src/components/side-navigation/side-navigation.test.tsx
packages/comet-uswds/src/components/side-navigation/side-navigation.tsx

Update all applicable components with children to allow providing child content as either a dynamic list or as declarative child components.
- Updated Accordion, Breadcrumb, ErrorMessages, ProcessList, Side Navigation, Select for dynamic and declarative children
- Updated unit tests and stories to provide both item and child examples
- Updated exports
https://github.com/MetroStar/comet/issues/78
- Provide flexibility when using components with children
- Verified local unit testing and storybook testing
N/A

CSG-1032: Comet USWDS Components with children should allow rendering of React children or a list of items

---

packages/comet-cli/package.json
packages/comet-cli/src/constants.ts
packages/comet-cli/src/index.ts

- Added api command to Comet CLI
N/A
Additional CLI functionality
Local Testing
N/A

Add API support to Comet CLI

---

package-lock.json
packages/comet-extras/package.json
packages/comet-extras/src/components/toggle/toggle.style.css

This is to resolve a css styling issue which is causing validation errors when running unit tests.
- Replaced nested toggle css with more specific selectors
- Updated comet-extras to next patch version
N/A
- Fix jest log errors

Fix Comet Extras CSS

---

packages/comet-uswds/src/components/process-list/process-list.css
packages/comet-uswds/src/components/process-list/process-list.stories.tsx
packages/comet-uswds/src/components/process-list/process-list.test.tsx
packages/comet-uswds/src/components/process-list/process-list.tsx

The current process list component does not allow indicating which step is current and/or completed. This update adds a currentStep prop to the component, which is then used to style the process list items based on the current step.
- Updated to allow setting current step on process list component
- Added new story fro current step
- Added new unit test
N/A
- Make the component more useful

Add Current Step Support to Process List

---

package-lock.json
packages/comet-extras/package.json
packages/comet-extras/src/components/data-table/data-table.tsx

Currently if the datatable page size or index is dynamically updated, the table does not rerender as expected. This update ensures the datatable paging provider is called when these values change.
- Update comet extras datatable to ensure paging is updated when pageSize and pageIndex changes
N/A
N/A
- Local Storybook Testing
- Published Beta package and tested in Comet Starter
N/A

Datatable Paging Fix

---

package-lock.json
packages/comet-uswds/package.json
packages/comet-uswds/src/components/alert/alert.test.tsx
packages/comet-uswds/src/components/alert/alert.tsx

The current alert component does not include all USWDS alert types. Adding missing emergency alert type.
- Added emergency type to alert component
- Added unit test for coverage
N/A
- Inline with USWDS

Add emergency type to alert component

---

packages/comet-uswds/src/components/checkbox/checkbox.stories.tsx
packages/comet-uswds/src/components/checkbox/checkbox.test.tsx
packages/comet-uswds/src/components/checkbox/checkbox.tsx
packages/comet-uswds/src/components/radio-button/radio-button.stories.tsx
packages/comet-uswds/src/components/radio-button/radio-button.test.tsx
packages/comet-uswds/src/components/radio-button/radio-button.tsx

Update USWDS Checkbox and Radio Button components to properly apply a default value when specified.
- Fixed checkbox default checked.
- Fixed radio button default checked.
- Added basic single checkbox and radio button stories.
#209 
- Bug fix

Fix: Checkbox component to work well with useForm

---

packages/comet-uswds/src/components/table/table.tsx

Currently the USWDS table renders data in the reverse order of `sortDir` prop provided. After reviewing, it appears that the initial aria-sort value is being overwrote when the USWDS `table.on()` function is being called. In order to fix the issue, this updates resets the value back.
- Updated to swap sortDir value provided to aria-sort
Fixes #229 
- Bug fix

USWDS Table Default Sorting Rendering Inverse

---

package-lock.json
packages/comet-uswds/package.json
packages/comet-uswds/src/components/form/form.stories.tsx
packages/comet-uswds/src/components/form/form.tsx

Update to ensure forms can be made more responsive.
- Removed hardcoded max width on form component
- Updated Contact Form example with USWDS mobile max width class
N/A
- Adhere to USWDS defaults
- More easily configurable

Remove Hardcoded Form Max Width

---

packages/comet-uswds/src/components/form/form.stories.tsx
packages/comet-uswds/src/components/pagination/pagination.stories.tsx
packages/comet-uswds/src/components/step-indicator/step-indicator.stories.tsx

- Removed wrappers from stories to allow storybook to display full code example.
- Misc cleanup
N/A
- Better Code Examples

Fix Stories with Wrapper Components

---

package-lock.json
packages/comet-uswds/package.json
packages/comet-uswds/src/components/button/button.stories.tsx
packages/comet-uswds/src/components/button/button.test.tsx
packages/comet-uswds/src/components/button/button.tsx

Currently the Big version of the USWDS button is provided as a variant, preventing the button from being rendered as big and some other color variant. This update adds size as a new prop, allowing any variant to be used with any size.
- Updated button to provide Big variant through size prop
- Updated unit tests and stories to reflect the change
- Updated comet-uswds to next minor version
N/A
- Provide additional button variations

Big Button Updates

---

package-lock.json
packages/comet-uswds/package.json
packages/comet-uswds/src/components/file-input/file-input.stories.tsx
packages/comet-uswds/src/hooks/index.ts
packages/comet-uswds/src/hooks/use-file-input.test.tsx
packages/comet-uswds/src/hooks/use-file-input.tsx

The current implementation of the File Input, based on the USWDS implementation doesn't provide a simple way to clear files. This update adds a new useFileInput custom hook, with a clear function to support current needs.
- Added file input custom hook with clear function
- Added file input story with clear button
- Added base hook unit tests
Implementation is based on how USWDS currently clears the input when the files are changed here: https://github.com/uswds/uswds/blob/e6a8bb2670e00cbd57177eb8c19d34313b7a53bb/packages/usa-file-input/src/index.js#L259 
Supports #262 
- Simplify clearing the File Input field
- Local Testing in Storybook
- Beta Testing in Comet Starter App
N/A

Add Custom File Input Hook

---

packages/comet-uswds/src/components/alert/alert.stories.tsx
packages/comet-uswds/src/components/alert/alert.style.css
packages/comet-uswds/src/components/alert/alert.test.tsx
packages/comet-uswds/src/components/alert/alert.tsx

While the USWDS alert doesn't provide a specification for closing an alert, it is a common use to allow closing the alert by clicking a close action on the alert. This update adds new props to support that use case.
- Added new allowClose and onClose props to support closing alerts
- Updated alert component to display close button when allowClose is true
- Updated alert component to run onClose callback when provided and alert is closed
- Updated alert styling to ensure body width is not restricted (this ensure the close action is properly right justified)
- Added new Allow Close story
- Added and updated unit tests
N/A
- Support common use case of closing an alert

Add Close Action to the USWDS Alert

---

packages/comet-uswds/src/components/index.ts
packages/comet-uswds/src/components/language-selector/index.ts
packages/comet-uswds/src/components/language-selector/language-selector.stories.tsx
packages/comet-uswds/src/components/language-selector/language-selector.test.tsx
packages/comet-uswds/src/components/language-selector/language-selector.tsx
packages/comet-uswds/src/uswds/types.d.ts

Currently Comet USWDS does not provide an implementation for the USWDS Language Selector. This PR is to add it as a new component.
Based on the following USWDS component: https://designsystem.digital.gov/components/language-selector/ 
- Added language selector component to comet-uswds
- Added stories and unit tests for coverage
- Added to exports
N/A
- Adding Newer USWDS Component to Comet

Add Language Selector Component to Comet USWDS

---

packages/comet-uswds/src/components/in-page-navigation/in-page-navigation.stories.tsx
packages/comet-uswds/src/components/in-page-navigation/in-page-navigation.test.tsx
packages/comet-uswds/src/components/in-page-navigation/in-page-navigation.tsx
packages/comet-uswds/src/components/in-page-navigation/index.ts
packages/comet-uswds/src/components/index.ts
packages/comet-uswds/src/uswds/types.d.ts

Currently Comet USWDS does not provide an implementation for the USWDS In-Page Navigation This PR is to add it as a new component.
Based on the following USWDS component: https://designsystem.digital.gov/components/in-page-navigation/
- Added in-page-navigation component
- Added unit tests and stories for coverage
- Add to exports
N/A
- Adding Newer USWDS Component to Comet

Add In-Page Navigation Component to Comet USWDS

---

package-lock.json
packages/comet-uswds/package.json
packages/comet-uswds/src/components/icon/icon.tsx
packages/comet-uswds/src/components/modal/modal.tsx
packages/comet-uswds/src/components/pagination/pagination.tsx

Updating @uswds/uswds package to 3.11.0. This also included some removal of svg attributes on hrefs.
git push --set-upstream origin upudate-uswds-3-11-0
Needed to update the uswds package to the latest version.
Locally ran clean of test and no noticeable differences with svgs or tables.

Updating uswds package with dependencies and href

---

packages/comet-extras/src/components/index.ts
packages/comet-extras/src/components/toast/index.ts
packages/comet-extras/src/components/toast/toast.stories.tsx
packages/comet-extras/src/components/toast/toast.style.css
packages/comet-extras/src/components/toast/toast.test.tsx
packages/comet-extras/src/components/toast/toast.tsx

Adds toast component with storybook and testing.
https://metrostarsys.sharepoint.com/sites/FrontendDevCoP/Lists/Tasks/DispForm.aspx?ID=24&e=GkVxp1
Want to add a toast notification to the extras.
Tests created and run locally.

Add toast component to extras

---

package-lock.json
packages/comet-data-viz/package.json
packages/comet-extras/package.json
packages/comet-uswds/package.json

- Removed react dependencies from react-based packages for peer deps in order to better support multiple versions of react.
- Updated packages to next patch version
N/A
- Explict react version dependencies was leading to conflicting react versions when used in react 18 app
- Deployed beta testing
N/A

Remove React Dependencies from Packages

---

package-lock.json
package.json

This PR updates dependencies from original PR here: #326. 
- Update vitest, rollup, and typescript-eslint to latest
N/A
- Issues with original PR. Updating manually
- Pipeline passing

Bump Patches to Latest

---

.github/dependabot.yml
.github/workflows/code-quality.yaml

- Updated dependabot to run on cron
- Added explicit permissions to code quality job to CodeQL scan
N/A
- Standardize dependabot scanning
- Resolve CodeQL warning
N/A

Action Updates
