packages/comet-uswds/src/components/card/card.stories.tsx, packages/comet-uswds/src/components/card/card.test.tsx, packages/comet-uswds/src/components/card/card.tsx, packages/comet-uswds/src/components/file-input/file-input.tsx
A few issues noted while making use of components in react app.
- Updated Card component to better support passing in a custom class
- Fixed File Input component, preventing unnecessary component re-rendering
N/A
General component improvements and fixes
Verified locally in storybook
=> Misc component fixes

packages/comet-uswds/package.json
New Release
- Update comet-uswds with new version
N/A
Create new release
N/A
N/A
=> Release: 1.0.1

packages/comet-extras/src/components/index.ts, packages/comet-extras/src/components/spinner/index.ts, packages/comet-extras/src/components/spinner/spinner.stories.tsx, packages/comet-extras/src/components/spinner/spinner.style.css, packages/comet-extras/src/components/spinner/spinner.test.tsx, packages/comet-extras/src/components/spinner/spinner.tsx
Add custom spinner component to comet extras for use in project.
- Added new Spinner component to Comet Extras
- Added unit tests and stories for new component
- Added to component exports
N/A
Common component used on projects
- Tested locally in storybook
- Verified all code quality checks pass
=> CSG-718: Add Custom Spinner component to Comet Extras

package-lock.json, packages/comet-uswds/package.json
Dependency Upgrades
- Updated comet-uswds to latest uswds 3.5.0 version.
- https://github.com/uswds/uswds/releases/tag/v3.5.0
- Dependency updates, which include accessibility enhancements
- Manual testing of all USWDS components
- Verified Code Quality checks
N/A
=> CSG-738: Upgrade Comet to USWDS 3.5.0

packages/comet-uswds/src/components/index.ts, packages/comet-uswds/src/components/select/index.ts, packages/comet-uswds/src/components/select/select.stories.tsx, packages/comet-uswds/src/components/select/select.test.tsx, packages/comet-uswds/src/components/select/select.tsx
Updates to replace dropdown with select component as updated by USWDS.
- Added new select component based on dropdown component
- Added deprecated language to dropdown
- Removed dropdown stories
N/A
- Inline with recent USWDS changes
Verified all tests, same as dropdown
N/A
=> CSG-742: Rename Comet USWDS Dropdown component to Select to match recent USWDS change

package-lock.json, packages/comet-uswds/package.json
Create new release
- Updated comet-uswds to next minor version.
N/A
N/A
N/A
N/A
=> Release: 1.3.0

package-lock.json, packages/comet-uswds/package.json
New Release
- Updated to next comet-uswds patch version.
N/A
N/A
N/A
N/A
=> Release: 1.3.1

packages/comet-uswds/src/components/modal/modal.stories.tsx, packages/comet-uswds/src/components/modal/modal.tsx
Misc Updates to Modal based on Comet Starter App use.
- Updated modal component to remove the embedded div and paragraph elements and provide body as only the passed in children
- Updated default stories to utilize data-close-modal attribute
- Added new story to provide implementation using toggleModal instead of attribute
N/A
- Prevent accessibility issues in Modal use
- Provide better story examples
- Tested Locally
N/A
=> CSG-886: Modal Accessibility and Story Updates

package-lock.json, packages/comet-uswds/package.json
New Release
- Updated to next uswds-comet patch release.
N/A
N/A
N/A
N/A
=> Release: 1.3.2

package-lock.json, packages/comet-uswds/package.json
New Release
- Updated to next uswds-comet patch release.
N/A
N/A
N/A
N/A
=> Release: 1.3.3

LICENSE.md
License file updates
- Updated year and company info in license copyright info.
N/A
N/A
N/A
N/A
=> Update license copyright info

package-lock.json, packages/comet-extras/package.json
New Release
- Updated comet-extras to next minor version
N/A
N/A
N/A
N/A
=> Release: 1.2.0 (Comet Extras)

package-lock.json, packages/comet-uswds/package.json
New release
- Updated to next minor version
N/A
N/A
N/A
N/A
=> Release: 1.5.0

.storybook/main.js, .storybook/preview.js, packages/comet-uswds/src/style-guide/Colors.mdx, packages/comet-uswds/src/style-guide/Icons.mdx, packages/comet-uswds/src/style-guide/Typography.mdx, packages/comet-uswds/src/style-guide/Welcome.mdx
Provide additional context for Comet and USWDS styling.
- Added Welcome Page
- Added Style Guide section with Colors, Typography, and Icons Pages
- Updated Storybook Sort Order
N/A
- Provide additional context
- Reduce the need to go to USWDS site for style guide details
- Local Storybook Testing
=> CSG-771: Add Welcome Page and Style Guide to Comet Storybook

package-lock.json, packages/comet-extras/package.json
New Release
- Updated comet extras to next patch release.
N/A
N/A
N/A
N/A
=> Release: 1.2.1 (Comet Extras)

package-lock.json, packages/comet-uswds/package.json
New Release
- Updated comet-uswds to next major release.
N/A
- This release contains breaking changes such that it removes USWDS css from the package and leaves that up to the consuming app.
N/A
N/A
=> Release: 2.0.0

README.md, package-lock.json, package.json, packages/comet-cli/LICENSE.md, packages/comet-cli/README.md, packages/comet-cli/fonts/Standard.flf, packages/comet-cli/package.json, packages/comet-cli/rollup.config.js, packages/comet-cli/src/constants.ts, packages/comet-cli/src/index.ts, packages/comet-cli/tsconfig.json
New package to simplify the process of creating Comet Apps
- Added comet-cli package to project
- Update project configs and readme for new package
N/A
- Simplify the process of creating Comet Starter Apps
- Verified app creation from fresh NPM install
=> CSG-635: Create CLI tool for creating Comet bootstrapped Apps

packages/comet-uswds/src/style-guide/Icons.mdx
- Updated link to mdx style link to fix deployed URL issue.
N/A
- Link fix
- Local testing passed
N/A
=> Icon link fix

package-lock.json, packages/comet-uswds/package.json
Dependency Upgrades
- Updated comet-uswds to latest uswds 3.7.0 version.
- N/A
- Dependency updates, which include USWDS enhancements and fixes
- Manual testing of all USWDS components
- Verified Code Quality checks
N/A
=> CSG-1156: Upgrade Comet to USWDS 3.7.0

package-lock.json, packages/comet-uswds/package.json
New Release
- Updated comet-uswds to next patch version
N/A
N/A
N/A
N/A
=> Release: 2.0.1

package-lock.json, package.json
Resolve Security Vulnerabilities
- Updated testing library package to latest to resolve vulnerability.
N/A
Maintenance
Local testing
N/A
=> Resolve Security Vulnerabilities - 12/23

packages/comet-extras/src/components/index.ts, packages/comet-extras/src/components/toggle/index.ts, packages/comet-extras/src/components/toggle/toggle.stories.tsx, packages/comet-extras/src/components/toggle/toggle.style.css, packages/comet-extras/src/components/toggle/toggle.test.tsx, packages/comet-extras/src/components/toggle/toggle.tsx
Added a toggle component to Comet. Used code from jhub-apps. Removed tailwind styles and added style to component highly reflecting jhub-apps syles. Chanded to USWDs branding colors
=> comet-ui-toggle-comp # added toggle component to comet

package-lock.json, packages/comet-extras/package.json, packages/comet-extras/src/components/toggle/toggle.tsx
New Release
- Updated comet extras to next minor release.
N/A
N/A
N/A
N/A
=> Release: 1.3.0 (Comet Extras)

package-lock.json, packages/comet-cli/package.json, packages/comet-data-viz/package.json, packages/comet-extras/package.json, packages/comet-uswds/package.json
New Release
- Update all comet packages to next patch release.
N/A
New Release
N/A
N/A
=> Release: 2.0.3

package-lock.json, packages/comet-cli/package.json, packages/comet-data-viz/package.json, packages/comet-extras/package.json, packages/comet-uswds/package.json
New Release
- Update all comet packages to next patch release.
N/A
- Patching
N/A
N/A
=> Release: 2.0.4

package-lock.json, packages/comet-uswds/package.json
New Release
- Update comet-uswds to next minor release
N/A
- New Alert component functionality
N/A
=> Release: 2.1.0

package-lock.json, packages/comet-uswds/package.json
- Updated uswds package to latest
N/A
Routine maintenance
Local Testing
=> Update USWDS to 3.8.1

package-lock.json, packages/comet-cli/package.json, packages/comet-data-viz/package.json, packages/comet-extras/package.json, packages/comet-uswds/package.json
New Release
- Updated all packages to next release.
N/A
N/A
N/A
N/A
=> Release: 2.1.1

package-lock.json, packages/comet-uswds/package.json, packages/comet-uswds/src/components/date-picker/date-picker.tsx
Fix USWDS Date Picker Re-render issue
- Fixed date picker rerender issue.
- Updated comet-uswds to next patch version.
- https://github.com/MetroStar/comet/issues/186
- https://github.com/MetroStar/comet/issues/186
- Tested locally
- Deployed beta version, tested in Comet Starter
N/A
=> Fix DatePicker duplication bug

package-lock.json, packages/comet-uswds/package.json
New Release
- Updated comet-uswds to next minor release.
#209 
- Bug fixes
N/A
N/A
=> Release: 2.3.0

README.md, packages/comet-data-viz/README.md, packages/comet-extras/README.md, packages/comet-uswds/README.md
The current docs do not provide very good setup steps. These updates should help with different types of setup.
- Updated main readme with links to packages.
- Updated package readmes with more specific instructions.
N/A
- Improved documentation
- Simplify Setup
N/A
N/A
=> Documentation Updates

eslint.config.js, package-lock.json, package.json, packages/comet-cli/src/index.ts, packages/comet-uswds/src/components/checkbox/checkbox.stories.tsx, packages/comet-uswds/src/components/form/form.stories.tsx, packages/comet-uswds/src/components/modal/modal.stories.tsx, packages/comet-uswds/src/components/pagination/pagination.stories.tsx, packages/comet-uswds/src/components/search/search.test.tsx
- Added more linting rules.
- Fixed linting errors.
- N/A
- Better Linting
N/A
=> Add More Linting Rules

package-lock.json, packages/comet-uswds/package.json
New Release
- Updated comet uswds to next minor version.
N/A
N/A
N/A
=> Release: 2.4.0

package-lock.json, packages/comet-uswds/package.json
New Release
- Updated comet-uswds to next patch release.
#229 
#219 
- Bug fix
N/A
=> Release: 2.4.1

package-lock.json, packages/comet-uswds/README.md, packages/comet-uswds/package.json
Next Major Release, including major form enhancements and bug fixes.
- Updated to next major release version.
#241 
- New Release
N/A
N/A
=> Release: 3.0.0

packages/comet-uswds/src/components/site-alert/site-alert.stories.tsx
- Updated site alert story to provide body as children to the component
N/A
- Better documentation
=> Update site alert story to provide body

package-lock.json, packages/comet-cli/README.md, packages/comet-cli/package.json, packages/comet-cli/src/constants.ts, packages/comet-cli/src/index.ts, packages/comet-cli/src/utils.ts
Enhance existing CLI with base generator commands. These commands are intended to provide generator/scaffolding functionality to the CLI, specific to Comet.
- Generalized UI and API init commands (comet init)
- Added new Generator Commands (comet add) for Pages and Components
- Updated Readme with examples
- Updated comet-cli to next minor version
N/A
- Enhance Comet Developer Experience
=> Comet CLI Generator Commands

figma.config.json, packages/comet-data-viz/src/components/area-graph/area-graph.figma.tsx, packages/comet-data-viz/src/components/bar-graph/bar-graph.figma.tsx, packages/comet-data-viz/src/components/line-graph/line-graph.figma.tsx, packages/comet-data-viz/src/components/pie-chart/pie-chart.figma.tsx, packages/comet-data-viz/src/components/polar-axis/polar-axis.figma.tsx, packages/comet-data-viz/src/components/scatter-graph/scatter-graph.figma.tsx
- Added code connect files for data viz components.
- Updated figma config to include data viz.
N/A
- Enhance existing code connect setup
- Published to UI Kit
=> Add Data Viz to Code Connect

packages/comet-uswds/src/components/process-list/process-list.figma.tsx, packages/comet-uswds/src/components/side-navigation/side-navigation.figma.tsx
- Cleanup code connect files for process list and side navigation to provide better code examples.
N/A
N/A
N/A
N/A
=> Code Connect Cleanup

package-lock.json, packages/comet-uswds/package.json, packages/comet-uswds/src/components/card/card.figma.tsx, packages/comet-uswds/src/components/card/card.stories.tsx, packages/comet-uswds/src/components/card/card.test.tsx, packages/comet-uswds/src/components/card/card.tsx, packages/comet-uswds/src/components/card/index.ts, packages/comet-uswds/src/components/index.ts
Updates to better support USWDS Card use-cases
- Added CardMedia component to Card exports
- Updated Card to support Default and Flag Layout
- Updated Card to support mediaRight Prop
- Updated unit tests and stories for card enhancements
- Update Figma Code Connect file for new functionality
N/A
- Better USWDS layout support
=> Card Updates

figma.config.json, packages/comet-data-viz/src/components/stack-graph/stack-graph.figma.tsx, packages/comet-extras/src/components/spinner/spinner.figma.tsx, packages/comet-extras/src/components/tabs/tabs.figma.tsx, packages/comet-extras/src/components/toggle/toggle.figma.tsx
- Added code connect files for comet extras components
- Updated figma config for comet extras
N/A
- Add remaining components to code connect
N/A
=> Add Comet Extras to Code Connect

package-lock.json, packages/comet-data-viz/package.json, packages/comet-extras/package.json
- Updated comet extras to next patch version
- Updated comet data viz to next patch version
N/A
- New Release
- Documentation Updates
N/A
N/A
=> Comet Extras/Data Viz September 2024 Release

package-lock.json, package.json
- Upgraded storybook to latest.
N/A
- Routine maintenance
=> Upgrade Storybook to 8.3.0

.github/workflows/code-quality.yaml, packages/comet-data-viz/rollup.config.mjs, packages/comet-extras/rollup.config.mjs, packages/comet-uswds/rollup.config.mjs, tsconfig.base.json
Ensure packages build on pull request into main.
- Added build step to code quality checks 
- Fixed dts build in rollup scripts
N/A
- Ensure build before merge
N/A
=> Add Build Step to Code Quality Checks

package-lock.json, packages/comet-uswds/package.json
New Release
- Updated comet-uswds to next minor release.
N/A
- New Release
N/A
N/A
=> Release 3.4.0

package-lock.json, packages/comet-uswds/package.json
New Release
- Updated comet-uswds to next minor release.
N/A
N/A
N/A
N/A
=> Release 3.5.0

.github/workflows/code-quality.yaml, packages/comet-uswds/src/components/index.ts, packages/comet-uswds/src/components/language-selector/index.ts, packages/comet-uswds/src/components/language-selector/language-selector.tsx
A few updates for consistency and testing
- Updated language selector exports for consistency with other similar components
- Updated code quality workflow action to run tests with coverage
N/A
- Updates for consistency
- Improve Testing
N/A
=> Misc Cleanup

package-lock.json, packages/comet-uswds/package.json
New Release
- Updated comet-uswds to next minor release.
N/A
N/A
N/A
N/A
=> Release 3.6.0

package-lock.json, package.json
- Updated optional dependency
- Include audit fixes
N/A
- Security updates
=> Package Lock Refresh

package-lock.json, packages/comet-uswds/package.json, packages/comet-uswds/src/components/memorable-date/memorable-date.tsx
Upgrade USWDS to latest in order to include recent fixes and updates
- Updated USWDS to 3.9.0
- Updated memorable date component as recommended in USWDS release notes
N/A
- Routine Updates
N/A
=> Upgrade to USWDS 3.9.0

package-lock.json, packages/comet-uswds/package.json
New Release
- Updated comet-uswds to next patch version.
N/A
- New USWDS Release
N/A
N/A
=> Release 3.6.1

eslint.config.js, package-lock.json, package.json, packages/comet-uswds/src/components/accordion/accordion.tsx, packages/comet-uswds/src/components/language-selector/language-selector.tsx
Add new React Hook Plugin for ESLint
- Added eslint-plugin-react-hooks to project and update configs
- Fixed linting errors
N/A
- Additional Linting Rules
N/A
=> Add ESLint Plugin React Hooks

eslint.config.js
- Updates to ESLint config for better organization with flat config
N/A
- Better organization
N/A
=> ESLint Cleanup

package-lock.json, packages/comet-uswds/package.json, packages/comet-uswds/src/components/step-indicator/step-indicator.tsx, packages/comet-uswds/src/components/time-picker/time-picker.stories.tsx
- Updated USWDS to 3.10.0
- Removed aria-label as suggested in USWDS release notes
- Updated time picker story hint as suggested in USWDS release notes
See USWDS release for more information: https://github.com/uswds/uswds/releases/tag/v3.10.0
N/A
- Routine patching
N/A
=> Upgrade USWDS to 3.10.0

package-lock.json, packages/comet-uswds/package.json
- Updated comet-uswds to next patch version.
N/A
N/A
N/A
N/A
=> Release: 3.6.2

.github/workflows/build-and-deploy.yaml, .github/workflows/code-quality.yaml, .github/workflows/publish-package.yaml
- Updated workflow actions for node 20.
N/A
- Update to run tests in current recommended version
N/A
=> Update for Node 20 as base

package-lock.json, packages/comet-data-viz/package.json, packages/comet-extras/package.json, packages/comet-uswds/package.json
New Release
- Updated packages to next minor release
N/A
N/A
- Tested published beta packages
N/A
=> Release: 3.7.0

package-lock.json, packages/comet-uswds/package.json
New Release
- Updated comet-uswds to 3.7.1.
N/A
N/A
N/A
=> Release: 3.7.1

packages/comet-extras/src/components/toast/toast.stories.tsx, packages/comet-extras/src/components/toast/toast.style.css, packages/comet-extras/src/components/toast/toast.test.tsx, packages/comet-extras/src/components/toast/toast.tsx
Adding a placement prop to the toast prop to let users determine where the notification comes in from.
https://metrostarsys.sharepoint.com/sites/FrontendDevCoP/Lists/Tasks/DispForm.aspx?ID=36&e=dtPrIx
We want to give users the ability to choose where the notifications will slide in.
storybook and test scripts
=> Adding placement prop to toast with styles and keyframes.

package-lock.json, packages/comet-extras/package.json
- Updated comet-extras to 1.6.0
=> Release: 1.6.0 (Comet Extras)

package-lock.json, packages/comet-extras/package.json, packages/comet-uswds/package.json
- Removed unnecessary peer dependencies from packages
- Updated packages to next patch version
N/A
- Cleanup
- Local testing
=> Peer Dependency Cleanup

package-lock.json, packages/comet-extras/package.json, packages/comet-uswds/package.json
- Added relative peer dependencies
- Update comet-uswds and comet-extras to next patch version
N/A
- Fix issue in last patch
- Local Testing, verified local build same as before
=> Relative Peer Dependencies

package-lock.json, packages/comet-uswds/package.json
- Updated USWDS to 3.10.0
See USWDS release for more information: https://github.com/uswds/uswds/releases/tag/v3.12.0
N/A
- Routine patching
N/A
=> Upgrade USWDS to 3.12.0

package-lock.json, packages/comet-uswds/package.json
- Updated to next patch release.
N/A
N/A
N/A
=> Release: 3.7.5

package-lock.json, packages/comet-cli/package.json, packages/comet-cli/src/index.ts
- Updated to clear and init new git history.
=> Initialize Comet Starter Clean

package-lock.json, packages/comet-extras/package.json, packages/comet-extras/src/components/data-table/data-table.tsx
Added a id, scope, and role attributes to table headers within the DataTable to be inline with the uswds core table for 508 compliance.
This change will help assistive technologies better understand table headers as the start of a column
Unit tests passed and all packages built locally
=> 508 Updates to Comet-Extras DataTable

package-lock.json, packages/comet-extras/package.json, packages/comet-extras/src/components/data-table/data-table.test.tsx, packages/comet-extras/src/components/data-table/data-table.tsx
- Updated applicable Datatable IDs to include table ID, to ensure uniqueness
- Updated unit tests for changes
- Updated comet-extras to next minor version
N/A
- Fix potential accessibility issues
=> Ensure Comet Extras Datatable IDs are Unique

package-lock.json, packages/comet-uswds/package.json, packages/comet-uswds/src/components/text-input/input-utils.ts
- Updated ssn mask pattern with correct regex
- Updated to next patch version
- N/A
- Bug Fix
=> Fix: SSN Mask Pattern

package-lock.json, packages/comet-uswds/package.json
- Updated comet-uswds to next patch version.
N/A
- New USWDS Release: https://github.com/uswds/uswds/releases/tag/v3.13.0 
N/A
=> Release: 3.7.7

packages/comet-extras/src/components/spinner/spinner.figma.tsx, packages/comet-extras/src/components/spinner/spinner.stories.tsx, packages/comet-extras/src/components/spinner/spinner.style.css, packages/comet-extras/src/components/spinner/spinner.test.tsx, packages/comet-extras/src/components/spinner/spinner.tsx
The appearance of the Comet Spinner was overhauled to be a rotating arc rather than moving dots, an additional property called textPosition was added to allow for loading text to be positioned to the left/right/top/bottom of the spinner, the loading text was set to be an empty string by default (optional), and 2 new spinner sizes (tiny and medium, the latter being the same size as the old large) were included.
https://metrostarsys.sharepoint.com/sites/FrontendDevCoP/Lists/Tasks/DispForm.aspx?ID=50&e=18GPBW
The spinner in its previous state had a more outdated appearance, and the related issue pushes for a more modern design.
https://metrostarsys.sharepoint.com/sites/FrontendDevCoP/Lists/Tasks/DispForm.aspx?ID=50&e=18GPBW
New unit tests have been added to provide the coverage needed for …
=> UI Overhaul/Changes for Spinner Component

package-lock.json, packages/comet-extras/package.json
- Updated comet-extras to next patch version.
N/A
- New Release
N/A
N/A
=> Comet Extras Release: 1.7.2

.vscode/extensions.json, .vscode/settings.json, package-lock.json, package.json
- Removed unused package
- Added vscode settings and extensions files to support local development
N/A
- Cleanup
- Improved developer experience
N/A
=> Misc Enhancements

package-lock.json, package.json
- Revert rollup package to support storybook build.
- https://github.com/rollup/rollup/issues/6012
- Fix Build
- Local Testing, builds fine with update
=> Bug: Fix Storybook Build

.github/workflows/code-quality.yaml
- Add coverage upload step to workflow.
N/A
- Support coverage badge in main readme
N/A
=> Upload Coverage Reports to Codecov

.github/workflows/code-quality.yaml, README.md
- Added badges to readme
- Updated workflow to fix codecov reporting
N/A
- Improve project transparency
=> Add README Badges

packages/comet-uswds/src/components/form-group/form-group.test.tsx, packages/comet-uswds/src/hooks/use-file-input.test.tsx
- Added Unit Tests for useFileInput and FormGroup for full coverage
N/A
- Increase coverage
=> Increase Code Coverage

package-lock.json, packages/comet-mcp/README.md, packages/comet-mcp/package.json, packages/comet-mcp/src/index.ts, packages/comet-uswds/README.md
- Added new add_comet tool to comet-mcp
- Updated readme with new tool
- Updated comet-uswds readme with new configs
- Updated to next minor version
N/A
- Simplify the installation of adding comet to an existing app
=> Implement add_comet MCP Tool
